apiVersion: apps/v1
kind: Deployment
metadata:
  name: content-web
  labels:
    app: content-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: content-web
  template:
    metadata:
      labels:
        app: content-web
    spec:
      containers:
      - name: content-web
        image: whatthehackmsft/content-web   
        env:
        - name: CONTENT_API_URL
          value: "http://content-api:3001"
        resources: 
          requests:
            cpu: "100m"
            memory: "128Mi"
        ports:
        - containerPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: content-api
  labels:
    app: content-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: content-api
  template:
    metadata:
      labels:
        app: content-api
    spec:
      containers:
      - name: content-api
        image: whatthehackmsft/content-api
        resources: 
          requests:
            cpu: "100m"
            memory: "128Mi"
        ports:
        - containerPort: 3001