apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    name: mongodb
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 27017
    targetPort: 27017
  selector:
    name: mongo-db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  mongo-db-deploy
  labels:
    name:  mongo-db
spec:
  selector:
    matchLabels:
      name: mongo-db
  template:
    metadata:
      labels:
        name:  mongo-db
    spec:
      containers:
      - image:  mongo
        name:  mongo-db-cntnr
        resources:
          requests:
            cpu: "200m"
            memory: "128Mi"
        ports:
        - containerPort:  27017
          name:  mongo-db
        volumeMounts:
        - mountPath: /data/db
          name: azuredisk-db
        - mountPath: /data/configdb
          name: azuredisk-configdb
      volumes:
        - name: azuredisk-db
          persistentVolumeClaim:
            claimName: datastoragepvc
        - name: azuredisk-configdb
          persistentVolumeClaim:
            claimName: configstoragepvc